name: Django CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Django system check
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          #DEBUG: "True"
          #DB_HOST: postgres
          #DB_PORT: "5432"
          #DB_NAME: forge
          #ALLOWED_HOSTS: "localhost,127.0.0.1,forge.local"
        run: |
          cd backend
          python manage.py check